### ISSUE TITLE
CS2 Window Track Problem

### ISSUE THREAD

**Issue by AK16bit** [JannesBonk/PassatHook#12]
If cs2 window is not fullscreen, passathook overlay will not be aligned. D:
![image](https://github.com/JannesBonk/PassatHook/assets/164229042/b29eb46c-395c-424d-b626-28fd68d0c0de)

**Comment by JannesBonk** [comment]
ey bro, got a question for ya. Are you using the perfect world version of CS2?

**Comment by AK16bit** [comment]
nah

**Comment by JannesBonk** [comment]
> nah

Alright

**Comment by JannesBonk** [comment]
Succesfully fixed the issue! An update will be coming soon addressing this issue
