### ISSUE TITLE
time

### ISSUE THREAD

**Issue by jett07** [JannesBonk/PassatHook#16]
how much time to fix this aimbot

**Comment by JannesBonk** [comment]
Showing me the issue + video with menu config instead of just saying "fix" would help much more

**Comment by jett07** [comment]
i play with your cheat but the aim is shaking

**Comment by JannesBonk** [comment]
> i play with your cheat but the aim is shaking like a milk shake

Provide a video so I can see the "shaking"

**Comment by jett07** [comment]
> > i play with your cheat but the aim is shaking like a milk shake
> 
> Provide a video so I can see the "shaking"

ok
