### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by Ryssiaczrk** [JannesBonk/PassatHook#17]
what cheats write to memory? avoiding those will make it pretty much ud

**Comment by JannesBonk** [comment]
> what cheats write to memory? avoiding those will make it pretty much ud

If you are talking about features in a cheat, in PassatHook, in the Miscellaneous->Main tab, you will see a switch labeled "Safe mode".

## Safe mode
- Disables the writing to memory feature
- Will reset all the features that write to memory (ex. Smoke modulation)

**Comment by Ryssiaczrk** [comment]
thank you so much
