### ISSUE TITLE
Injection issue

### ISSUE THREAD

**Issue by Unkn0wnKnown** [JannesBonk/PassatHook#3]
Hello! Im having an issue when trying to inject the cheat. So fist when i downloaded the exe file i opened it before cs2 was open and it said something like "Unable to get cs2 pid" or something like that then i opened cs2 and then opened the exe file and it said "Failed to update GlobalVars Cheat might be outdated" so is there anfix for this or is the cheat just outdated like it says. Best regards, Xulax.wtf

**Comment by JannesBonk** [comment]
> Hello! Im having an issue when trying to inject the cheat. So fist when i downloaded the exe file i opened it before cs2 was open and it said something like "Unable to get cs2 pid" or something like that then i opened cs2 and then opened the exe file and it said "Failed to update GlobalVars Cheat might be outdated" so is there anfix for this or is the cheat just outdated like it says. Best regards, Xulax.wtf

Hi there! Are you running the latest version from github? If so, maybe try running as admin. At the moment, it's 1:05AM for me, and I don't wanna get up and see if there is an issue.

**Comment by Unkn0wnKnown** [comment]
Oh yes i didnt run it as admin dumb me heh..

**Comment by Unkn0wnKnown** [comment]
yay got it to work by running as admin:D
