### ISSUE TITLE
visible check

### ISSUE THREAD

**Issue by Miguelxtrem** [JannesBonk/PassatHook#4]
visible check is broken

**Comment by JannesBonk** [comment]
> visible check is broken 

If you are talking about the visible check in aimbot, then yes I can agree with you, it's pretty broken. It is based on the CS2 radar, and that's the main reason it's so garbage

**Comment by Miguelxtrem** [comment]
oh alr i see so there is no possibility of fixing it then? 
btw you cheat is perfect W cheat. But how to use the grenade helper? i didn't figured it out yet.

**Comment by JannesBonk** [comment]
> oh alr i see so there is no possibility of fixing it then? 

I recommend not using it for now, probably later on I'll rework it.

> btw you cheat is perfect W cheat.

Thanks! 

> how to use the grenade helper? i didn't figured it out yet.

It's very simple, first you turn on the grenade helper, and config it to your liking. After that, if you want to add a location, you position yourself and aim where you need to aim (ex. Connector smoke: next to the trash can on T spawn, aiming at the first dot on the carpet, and you also need to jump), after that it's very easy, just open the menu, choose the condition the player needs to be in (in the example I gave, you select Jumping), and just add the location. I'll make a documentation on every function one day.

**Comment by Miguelxtrem** [comment]
alright i will try to use it thank you so much
