### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Drahna** [JannesBonk/PassatHook#6]
Creating a new config in the config manager unhooks the cheat, it launches fast so it isn't that big of a deal, but thought I'd mention it regardless.

**Comment by JannesBonk** [comment]
> Creating a new config in the config manager unhooks the cheat, it launches fast so it isn't that big of a deal, but thought I'd mention it regardless.

Can you please show a screen recording? I've tested it on my machine and it doesn't seem to happen.

**Comment by Drahna** [comment]
i can, give me a moment to record it, it might be a one time thing i caused somehow
